# Generated by Django 3.0.2 on 2020-02-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='74 Winthrop Street', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Cambridge', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='Massachusetts', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(default='02128', max_length=5),
        ),
    ]
