# Generated by Django 3.0.2 on 2020-02-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='purchase_history',
        ),
    ]
