# Generated by Django 3.0.2 on 2020-02-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(max_length=64)),
                ('is_small', models.BooleanField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
        ),
    ]
