# Generated by Django 3.0.2 on 2020-02-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=64, verbose_name='food')),
                ('small_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=64, verbose_name='food')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=64, verbose_name='food')),
                ('small_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pizza_type', models.CharField(choices=[('RG', 'Regular'), ('SC', 'Sicilian')], max_length=2)),
                ('pizza_styles', models.CharField(choices=[('CZ', 'Cheese'), ('1T', '1 Topping'), ('2T', '2 Toppings'), ('3T', '3 Toppings'), ('SP', 'Special')], max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=64, verbose_name='food')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=64, verbose_name='food')),
                ('small_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubsAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=64, verbose_name='food')),
                ('small_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=64, verbose_name='food')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
