# Generated by Django 3.0.2 on 2020-02-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dinnerplatter_pasta_pizza_salad_subs_subsaddition_topping'),
        ('orders', '0004_auto_20200211_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
