# Generated by Django 3.0.2 on 2020-02-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0002_auto_20200205_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_ordered',
            field=models.ManyToManyField(related_name='orders', to='menu.Menu'),
        ),
    ]
