# Generated by Django 3.0.2 on 2020-02-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_purchase_history'),
        ('menu', '0002_dinnerplatter_pasta_pizza_salad_subs_subsaddition_topping'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0003_order_items_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pizza_orders', to='menu.Pizza')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='items_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderedSubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_additions', models.ManyToManyField(related_name='subs_additions_orders', to='menu.SubsAddition')),
                ('subs_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subs_orders', to='menu.Subs')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedPizzaToppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderedPizza')),
                ('toppings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topping_orders', to='menu.Topping')),
            ],
        ),
        migrations.AddField(
            model_name='orderedpizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, through='orders.OrderedPizzaToppings', to='menu.Topping'),
        ),
        migrations.CreateModel(
            name='OrderedFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_ordered', to='orders.Order')),
            ],
        ),
    ]
