# Generated by Django 3.0.2 on 2020-03-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200305_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedfood',
            old_name='size',
            new_name='isSmall',
        ),
    ]
