# Generated by Django 3.0.2 on 2020-03-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200305_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedfood',
            old_name='price',
            new_name='itemPrice',
        ),
    ]
