# Generated by Django 3.0.2 on 2020-03-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_cooked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='addOnPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
